### PR TITLE
Update README.md - Add a link to "chronological-issues-from-video.md" that describes known issues with the video

### PR DESCRIPTION
**Pull request by freddie71010**
Add a link to "chronological-issues-from-video.md" that describes known issues with the video

### CODE REVIEW

**Comment by freddie71010** [comment]
@cromewar you think you can merge this in?

**Comment by cromewar** [comment]
> @cromewar you think you can merge this in? 

I always let this to @PatrickAlphaC, he must approve each merge to the repo, let's hope he have time to review this.

**Comment by PatrickAlphaC** [comment]
Thanks for the flag @cromewar  :)

**Comment by PatrickAlphaC** [comment]
And this looks good to me!

**Pull request merged**
